### ISSUE TITLE
Bundle path dependencies 

### ISSUE THREAD

**Issue by adriangb** [artisanofcode/poetry-stickywheel-plugin#14]
I realize it’s not the goal of this project at all, but given that you’ve touched internals in the general area I’m curious if you have any sense of how possible it might be to _bundle_ path dependencies into the wheel instead of replacing them with a published version. I imagine it would involve (1) figuring out how to manage the source files and (2) pulling the child dependencies into the top level package.

**Comment by danielknell** [comment]
I'm not sure I want to go that path here, it would add a lot of complexity and involve rewriting the build command to combine the separate packages into a single distribution.

that's something that would be better served with a different extension.
